import { type AppState, type Booking, endTime } from "./model";
const staff = [
  { id: "jessica", name: "Jessica", role: "Hair stylist", initials: "JE" },
  { id: "amaka", name: "Amaka", role: "Braiding specialist", initials: "AM" },
  { id: "linda", name: "Linda", role: "Nail artist", initials: "LI" },
];
const services = [
  {
    id: "haircut",
    name: "Signature haircut",
    description:
      "A fresh shape, a little confidence. Includes a consultation, wash, cut, and finish.",
    duration: 45,
    price: 8000,
    deposit: 0,
    staffIds: ["jessica"],
    active: true,
  },
  {
    id: "braids",
    name: "Knotless braids",
    description:
      "Lightweight, beautifully finished braids, made just for you. Extensions included.",
    duration: 180,
    price: 25000,
    deposit: 5000,
    staffIds: ["amaka", "jessica"],
    active: true,
  },
  {
    id: "nails",
    name: "Gel manicure",
    description:
      "Thoughtful nail care with a flawless, long-lasting gel finish.",
    duration: 60,
    price: 12000,
    deposit: 0,
    staffIds: ["linda"],
    active: true,
  },
  {
    id: "styling",
    name: "Hair styling",
    description:
      "For your everyday moments and your special ones. Wash, treatment, and styling.",
    duration: 120,
    price: 15000,
    deposit: 3000,
    staffIds: ["jessica", "amaka"],
    active: true,
  },
  {
    id: "consult",
    name: "Hair consultation",
    description:
      "A little time to talk about your hair and find what works for you.",
    duration: 30,
    price: 3000,
    deposit: 0,
    staffIds: ["jessica", "amaka"],
    active: true,
  },
  {
    id: "pedicure",
    name: "Classic pedicure",
    description:
      "Soak, soften, and slow down. A complete refresh for your feet.",
    duration: 60,
    price: 10000,
    deposit: 0,
    staffIds: ["linda"],
    active: true,
  },
];
const customers = [
  {
    id: "sarah",
    name: "Sarah Johnson",
    phone: "+234 803 555 0124",
    notes: "Prefers a quiet appointment. Usually books with Jessica.",
  },
  {
    id: "amaka-obi",
    name: "Amaka Obi",
    phone: "+234 806 555 0192",
    notes: "Medium knotless braids. Sensitive scalp; keep tension light.",
  },
  {
    id: "tolu",
    name: "Tolu Ade",
    phone: "+234 809 555 0146",
    notes: "Loves a neutral gel finish.",
  },
  { id: "grace", name: "Grace Okafor", phone: "+234 802 555 0168", notes: "" },
  {
    id: "david",
    name: "David Eze",
    phone: "+234 805 555 0173",
    notes: "Short on the sides, textured on top.",
  },
  {
    id: "ada",
    name: "Ada Nwosu",
    phone: "+234 810 555 0182",
    notes: "First-time visitor. Interested in a natural hair care routine.",
  },
];
function booking(
  id: string,
  code: string,
  customerId: string,
  serviceId: string,
  staffId: string,
  day: string,
  hour: string,
  status: Booking["status"] = "Confirmed",
): Booking {
  const startTime = `2026-09-${day}T${hour}:00`;
  return {
    id,
    code,
    businessId: "bloom",
    customerId,
    serviceId,
    staffId,
    startTime,
    endTime: endTime(
      startTime,
      services.find((s) => s.id === serviceId)!.duration,
    ),
    status,
    notes: "",
    createdAt: "2026-09-10T16:32:00",
    reminder: "2026-09-12T08:00:00",
    activity: [
      {
        id: `${id}-1`,
        title: "Reservation created",
        time: "2026-09-10T16:32:00",
        actor: "owner",
      },
      ...(status !== "Needs confirmation"
        ? [
            {
              id: `${id}-2`,
              title: "Customer confirmed",
              time: "2026-09-11T09:14:00",
              actor: "customer" as const,
            },
          ]
        : []),
    ],
  };
}
export const seed: AppState = {
  loaded: false,
  business: {
    id: "bloom",
    name: "Bloom Studio",
    slug: "bloom-studio",
    owner: "Jessica",
    category: "Hair & beauty",
    description:
      "A little time for yourself. We’re a thoughtful hair and beauty studio in the heart of Abuja, creating looks that feel like you. Come as you are. Leave feeling a little more yourself.",
    phone: "+234 803 555 0100",
    address: "14 Adetokunbo Ademola Crescent, Wuse 2, Abuja",
    hours: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ].map((day) => ({
      day,
      open: "09:00",
      close: day === "Saturday" ? "18:00" : "19:00",
      closed: day === "Sunday",
    })),
    bookingPolicy:
      "Please arrive 10 minutes before your appointment. Book up to 60 days ahead, with at least 30 minutes’ notice.",
    cancellationPolicy:
      "Plans change. Please reschedule or cancel at least 24 hours before your appointment so we can offer your time to someone else.",
    depositPolicy:
      "Selected services require a deposit paid directly to the studio. Your deposit goes toward the cost of your service.",
    faqs: [
      {
        question: "Do I need to bring hair extensions?",
        answer:
          "No, extensions are included with our knotless braids service. Let us know your preferred colour when you book.",
      },
      {
        question: "Can I walk in?",
        answer:
          "Walk-ins are welcome when we have space. Booking ahead is the best way to reserve your preferred time.",
      },
    ],
    rules: { minNoticeMinutes: 30, maxAdvanceDays: 60, slotMinutes: 30 },
  },
  staff,
  services,
  customers,
  bookings: [
    booking(
      "b1",
      "7FQ9KD",
      "sarah",
      "haircut",
      "jessica",
      "12",
      "09:00",
      "Completed",
    ),
    booking(
      "b2",
      "A82LPR",
      "amaka-obi",
      "braids",
      "amaka",
      "12",
      "10:30",
      "Needs confirmation",
    ),
    booking("b3", "M4X2JT", "tolu", "nails", "linda", "12", "14:00"),
    booking("b4", "K9R3WN", "grace", "styling", "jessica", "12", "15:00"),
    booking(
      "b5",
      "P6T8YA",
      "david",
      "haircut",
      "jessica",
      "12",
      "17:15",
      "Pending",
    ),
    booking(
      "b6",
      "B3H7VC",
      "ada",
      "consult",
      "amaka",
      "07",
      "09:00",
      "Completed",
    ),
    booking(
      "b7",
      "R8N2GA",
      "grace",
      "styling",
      "jessica",
      "07",
      "11:00",
      "Completed",
    ),
    booking(
      "b8",
      "D5K9FM",
      "sarah",
      "nails",
      "linda",
      "08",
      "10:00",
      "Completed",
    ),
    booking(
      "b9",
      "H4J7WL",
      "david",
      "haircut",
      "jessica",
      "09",
      "09:30",
      "Completed",
    ),
    booking(
      "b10",
      "N6V3PT",
      "ada",
      "braids",
      "amaka",
      "09",
      "13:00",
      "Completed",
    ),
    booking(
      "b11",
      "W9F2RA",
      "tolu",
      "pedicure",
      "linda",
      "10",
      "11:00",
      "Completed",
    ),
    booking(
      "b12",
      "E8Y5KB",
      "grace",
      "styling",
      "jessica",
      "11",
      "10:00",
      "Completed",
    ),
    booking(
      "b13",
      "C2M6HD",
      "sarah",
      "styling",
      "jessica",
      "11",
      "14:30",
      "Cancelled",
    ),
    booking("b14", "L7X4QF", "tolu", "nails", "linda", "16", "12:00"),
    booking("b15", "T3G9NP", "ada", "braids", "amaka", "19", "14:00"),
  ],
  agentActivity: [
    {
      id: "a1",
      title: "Confirmed Sarah’s appointment",
      detail: "Sarah confirmed her 9:00 AM signature haircut.",
      time: "Yesterday, 4:32 PM",
      kind: "confirmed",
    },
    {
      id: "a2",
      title: "Made a little room for David",
      detail: "Moved his haircut from 4:30 PM to 5:15 PM.",
      time: "Yesterday, 2:18 PM",
      kind: "rescheduled",
    },
    {
      id: "a3",
      title: "Welcomed a new reservation",
      detail: "Booked a gel manicure for Tolu on September 16.",
      time: "September 10, 11:06 AM",
      kind: "created",
    },
  ],
  settings: { reminders: true, confirmations: true, owner: "Jessica" },
};
