"use client";
import { Skeleton } from "./ui/skeleton";

type Kind = "calendar" | "table" | "cards" | "details" | "profile" | "payment" | "form" | "auth";
function Header() { return <div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div className="space-y-3"><Skeleton className="h-3 w-28" /><Skeleton className="h-8 w-52 max-w-full" /><Skeleton className="h-4 w-64 max-w-full" /></div><Skeleton className="h-10 w-32 rounded-xl" /></div>; }
function Form(){return <div className="space-y-5 rounded-[22px] bg-card p-6">{[0,1,2].map(i=><div key={i} className="space-y-2"><Skeleton className="h-3 w-28" /><Skeleton className="h-10 w-full rounded-xl" /></div>)}<Skeleton className="h-10 w-32 rounded-xl" /></div>;}
function Content({kind}:{kind:Kind}) {
 if(kind==="auth")return <div className="mx-auto max-w-[440px] py-12"><Skeleton className="mx-auto mb-8 h-7 w-24" /><Form /></div>;
 if(kind==="payment")return <div className="grid min-h-[70vh] gap-8 lg:grid-cols-2"><div className="space-y-8 rounded-[28px] bg-primary p-8"><Skeleton className="h-4 w-36 bg-card/20" /><Skeleton className="h-20 w-3/4 bg-card/20" /><Skeleton className="h-60 w-full rounded-3xl bg-card/10" /></div><div className="space-y-6 py-6"><Skeleton className="h-9 w-48" /><Form /></div></div>;
 if(kind==="details")return <div className="mx-auto max-w-[760px]"><Skeleton className="mb-6 h-4 w-40" /><div className="space-y-7 rounded-[40px] bg-card p-7 sm:p-10"><Skeleton className="h-5 w-28" /><Skeleton className="h-20 w-4/5" /><div className="grid grid-cols-3 gap-3">{[0,1,2].map(i=><Skeleton key={i} className="h-20 rounded-2xl" />)}</div><div className="grid grid-cols-2 gap-3">{[0,1,2,3].map(i=><Skeleton key={i} className="h-28 rounded-2xl" />)}</div><Skeleton className="h-52 rounded-3xl" /></div></div>;
 if(kind==="profile")return <div className="mx-auto max-w-[760px] space-y-8 rounded-[40px] bg-card p-6 sm:p-10"><Header /><Skeleton className="h-60 rounded-[30px]" /><Skeleton className="h-5 w-32" /><div className="grid gap-4 sm:grid-cols-2">{[0,1,2,3].map(i=><Skeleton key={i} className="h-36 rounded-2xl" />)}</div></div>;
 return <><Header />{kind==="calendar"?<div className="overflow-hidden rounded-[22px] bg-card p-5"><div className="mb-5 flex justify-between"><Skeleton className="h-9 w-48" /><Skeleton className="h-9 w-24" /></div><div className="grid h-[480px] grid-cols-4 divide-x divide-border">{[0,1,2,3].map(i=><div key={i} className="space-y-6 px-3"><Skeleton className="mx-auto h-10 w-12" /><div className={i%2?"pt-20":"pt-6"}><Skeleton className="h-24 rounded-xl" /></div><Skeleton className="h-16 rounded-xl" /></div>)}</div></div>:kind==="cards"?<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{[0,1,2,3,4,5].map(i=><div key={i} className="space-y-5 rounded-[22px] bg-card p-6"><Skeleton className="h-11 w-11 rounded-xl" /><Skeleton className="h-5 w-3/4" /><Skeleton className="h-12 w-full" /><Skeleton className="h-4 w-24" /></div>)}</div>:kind==="form"?<div className="grid gap-5 lg:grid-cols-[220px_1fr]"><div className="space-y-3">{[0,1,2,3].map(i=><Skeleton key={i} className="h-10 w-full rounded-xl" />)}</div><Form /></div>:<div className="table-panel"><div className="table-toolbar"><Skeleton className="h-9 w-56 max-w-full" /><Skeleton className="h-10 w-60 max-w-full rounded-xl" /></div><Skeleton className="h-11 w-full rounded-none" />{[0,1,2,3,4].map(i=><div key={i} className="flex items-center gap-4 border-b border-border px-5 py-5"><Skeleton className="h-9 w-9 shrink-0 rounded-full" /><div className="min-w-0 flex-1 space-y-2"><Skeleton className="h-4 w-2/3" /><Skeleton className="h-3 w-1/3" /></div><Skeleton className="hidden h-4 w-24 sm:block" /><Skeleton className="h-6 w-20 rounded-full" /></div>)}</div>}</>;
}
export function RouteLoading({pathname="/",label="Loading…",withShell=false}:{pathname?:string;label?:string;withShell?:boolean}) {
 const kind:Kind=pathname==="/login"||pathname==="/onboarding"?"auth":pathname.startsWith("/pay/")?"payment":pathname.startsWith("/r/")||/^\/bookings\/.+/.test(pathname)?"details":pathname.startsWith("/b/")?"profile":pathname==="/"?"calendar":pathname==="/services"?"cards":["/settings","/business-profile","/agent"].includes(pathname)?"form":"table";
 return <div role="status" aria-busy="true" className={withShell?"min-h-screen bg-background lg:pl-[250px]":"w-full min-w-0"}><span className="sr-only">{label}</span>{withShell&&<aside aria-hidden="true" className="fixed left-9 top-10 hidden w-48 space-y-6 lg:block"><Skeleton className="h-7 w-24" /><Skeleton className="h-14 w-full rounded-xl" />{[0,1,2,3,4,5].map(i=><Skeleton key={i} className="h-9 w-full rounded-xl" />)}</aside>}<div aria-hidden="true" className="mx-auto w-full max-w-[1400px] p-5 sm:p-8"><Content kind={kind} /></div></div>;
}
